spring:
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

token:
  prefix: ${JWT_PREFIX}
  refreshPrefix: ${REFRESH_PREFIX}
  blackListPrefix: ${BLACK_PREFIX}
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${REFRESH_EXPIRATION}
  blackListExpiration: ${BLACK_EXPIRATION}

dummy:
  total_size: 50_000
  batch_size: 5_000


